# Generated by Django 4.0 on 2021-12-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potassium', models.CharField(max_length=200)),
                ('phosphorus', models.CharField(max_length=100)),
                ('Nitrogen', models.CharField(max_length=100)),
                ('Moistue', models.TextField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
